name: MakiScreen
description: Having fun!
version: 1.1.1
api-version: 1.17
main: cat.maki.MakiScreen.MakiScreen
commands:
  maki:
    description: Does things!
    usage: /<command>
  setMakiMaster:
    description: Sets the MakiMaster
    usage: /<command>
  setMakiSlave:
    description: Sets the MakiSlave
    usage: /<command>
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot